apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fermentation-station-agent-limit-docker-builds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lukasb27/fermentation-station-agent.git
    targetRevision: limit-docker-builds
    path: k8s
    kustomize:
      images:
        - lukasball/fermentation-station-agent=lukasball/fermentation-station-agent:limit-docker-builds
      commonAnnotations:
        prNumber: "21"
        sha: ccb1a09fcb2da62b0bf28bc0c10823c373d09872
  destination:
    server: https://kubernetes.default.svc
    namespace: limit-docker-builds
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true