apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fermentation-station-agent-sensor-factory
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lukasb27/fermentation-station-agent.git
    targetRevision: sensor-factory
    path: k8s
    kustomize:
      images:
        - lukasball/fermentation-station-agent=lukasball/fermentation-station-agent:sensor-factory
      commonAnnotations:
        prNumber: ""
        sha: 16ced64bcc9c38c01906fd95211e453d527ffcc6
  destination:
    server: https://kubernetes.default.svc
    namespace: sensor-factory
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true